# Generated by Django 5.0.7 on 2024-09-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                ("content", models.TextField(max_length=500, verbose_name="محتوا")),
                ("priority", models.IntegerField(default=1, verbose_name="اولویت")),
                ("is_done", models.BooleanField(verbose_name="انجام شده/نشده")),
            ],
            options={
                "verbose_name": "انجام کار",
                "verbose_name_plural": "انجام کارها",
            },
        ),
    ]
